---
title: "script"
author: "LAR"
date: "6/11/2021"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# libraries
```{r}
library(tidyverse)#data wrangling and manipulation 
library(readxl) #importing data
library(ggthemes) #plot customisation
library(rnaturalearth) #shape file
library(ggpubr) #plot customisation
library(psych) #descriptive statistics
```

# data 

## sunflower
```{r}
#2012-2013
sf_2013_1 <- read_xlsx("data/sunflower/sf_part_1_2012_2013.xls.xlsx")
sf_2013_2 <- read_xlsx("data/sunflower/sf_part_2_2012_2013.xls.xlsx")
sf_2013_3 <- read_xlsx("data/sunflower/sf_part_3_2012_2013.xls.xlsx")
sf_2013_4 <- read_xlsx("data/sunflower/sf_part_4_2012_2013.xls.xlsx")

#2013-2014
sf_2014_1 <- read_xlsx("data/sunflower/sf_part_1_2013_2014.xls.xlsx")
sf_2014_2 <- read_xlsx("data/sunflower/sf_part_2_2013_2014.xls.xlsx")
sf_2014_3 <- read_xlsx("data/sunflower/sf_part_3_2013_2014.xls.xlsx")
sf_2014_4 <- read_xlsx("data/sunflower/sf_part_4_2013_2014.xls.xlsx")

#2014-2015
sf_2015_1 <- read_xlsx("data/sunflower/sf_part_1_2014_2015.xls.xlsx")
sf_2015_2 <- read_xlsx("data/sunflower/sf_part_2_2014_2015.xls.xlsx")
sf_2015_3 <- read_xlsx("data/sunflower/sf_part_3_2014_2015.xls.xlsx")
sf_2015_4 <- read_xlsx("data/sunflower/sf_part_4_2014_2015.xls.xlsx")

#2015-2016
sf_2016_1 <- read_xlsx("data/sunflower/sf_part_1_2015_2016.xls.xlsx")
sf_2016_2 <- read_xlsx("data/sunflower/sf_part_2_2015_2016.xls.xlsx")
sf_2016_3 <- read_xlsx("data/sunflower/sf_part_3_2015_2016.xls.xlsx")


#2016-2017
sf_2017_1 <- read_xlsx("data/sunflower/sf_part_1_2016_2017.xls.xlsx")
sf_2017_2 <- read_xlsx("data/sunflower/sf_part_2_2016_2017.xls.xlsx")
sf_2017_3 <- read_xlsx("data/sunflower/sf_part_3_2016_2017.xls.xlsx")
sf_2017_4 <- read_xlsx("data/sunflower/sf_part_4_2016_2017.xls.xlsx")

#2017-2018
sf_2018_1 <- read_xlsx("data/sunflower/sf_part_1_2017_2018.xls.xlsx")
sf_2018_2 <- read_xlsx("data/sunflower/sf_part_2_2017_2018.xls.xlsx")
sf_2018_3 <- read_xlsx("data/sunflower/sf_part_3_2017_2018.xls.xlsx")
sf_2018_4 <- read_xlsx("data/sunflower/sf_part_4_2017_2018.xls.xlsx")

#2018-2019
sf_2019_1 <- read_xlsx("data/sunflower/sf_part_1_2018_2019.xls.xlsx")
sf_2019_2 <- read_xlsx("data/sunflower/sf_part_2_2018_2019.xls.xlsx")
sf_2019_3 <- read_xlsx("data/sunflower/sf_part_3_2018_2019.xls.xlsx")
sf_2019_4 <- read_xlsx("data/sunflower/sf_part_4_2018_2019.xls.xlsx")
#2019-2020
sf_2020_1 <- read_xlsx("data/sunflower/sf_part_1_2019_2020.xls.xlsx")
sf_2020_2 <- read_xlsx("data/sunflower/sf_part_2_2019_2020.xls.xlsx")
sf_2020_3 <- read_xlsx("data/sunflower/sf_part_3_2019_2020.xls.xlsx")
sf_2020_4 <- read_xlsx("data/sunflower/sf_part_4_2019_2020.xls.xlsx")
```

### join
```{r}
#2013
sf_201213_df <- sf_2013_1 %>% 
  full_join(sf_2013_2) %>% 
  full_join(sf_2013_3) %>% 
  full_join(sf_2013_4) %>% 
  mutate(harvest_year = 2013) %>% 
  rename(desc = Region) %>% 
  filter(desc %in% c("3. Sclerotia, %", "No. of samples")) %>% 
  distinct() %>%
 pivot_longer(cols = c(2:23),
               names_to = "region",
               values_to = "per_sclerotia") %>% 
  pivot_wider(names_from = "desc",
              values_from = "per_sclerotia") %>% 
  rename(per_scl = "3. Sclerotia, %",
         no_samples = "No. of samples")


#2014 
sf_201314_df <- sf_2014_1 %>% 
  full_join(sf_2014_2) %>% 
  full_join(sf_2014_3) %>% 
  full_join(sf_2014_4) %>% 
  mutate(harvest_year = 2014) %>% 
  rename(desc = Region) %>% 
    filter(desc %in% c("3. Sclerotia, %", "No. of samples")) %>% 
  distinct() %>%
 pivot_longer(cols = c(2:22),
               names_to = "region",
               values_to = "per_sclerotia") %>% 
  pivot_wider(names_from = "desc",
              values_from = "per_sclerotia") %>% 
  rename(per_scl = "3. Sclerotia, %",
         no_samples = "No. of samples")

#2015
sf_201415_df <- sf_2015_1 %>% 
  full_join(sf_2015_2) %>% 
  full_join(sf_2015_3) %>% 
  full_join(sf_2015_4) %>% 
  mutate(harvest_year = 2015) %>% 
  rename(desc = Region) %>% 
    filter(desc %in% c("3. Sclerotia, %", "No. of samples")) %>% 
  distinct() %>%
 pivot_longer(cols = c(2:24),
               names_to = "region",
               values_to = "per_sclerotia") %>% 
  pivot_wider(names_from = "desc",
              values_from = "per_sclerotia") %>% 
  rename(per_scl = "3. Sclerotia, %",
         no_samples = "No. of samples")

#2016
sf_201516_df <- sf_2016_1 %>% 
  full_join(sf_2016_2) %>% 
  full_join(sf_2016_3) %>% 
  mutate(harvest_year = 2016) %>% 
  rename(desc = Region) %>% 
    filter(desc %in% c("3. Sclerotia, %", "No. of samples")) %>% 
  distinct() %>%
 pivot_longer(cols = c(2:19),
               names_to = "region",
               values_to = "per_sclerotia") %>% 
  pivot_wider(names_from = "desc",
              values_from = "per_sclerotia") %>% 
  rename(per_scl = "3. Sclerotia, %",
         no_samples = "No. of samples")

#2017
sf_201617_df <- sf_2017_1 %>% 
  full_join(sf_2017_2) %>% 
  full_join(sf_2017_3) %>% 
  full_join(sf_2017_4) %>% 
  mutate(harvest_year = 2017) %>% 
  rename(desc = Region) %>% 
    filter(desc %in% c("3. Sclerotia, %", "No. of samples")) %>% 
  distinct() %>%
 pivot_longer(cols = c(2:20),
               names_to = "region",
               values_to = "per_sclerotia") %>% 
  pivot_wider(names_from = "desc",
              values_from = "per_sclerotia") %>% 
  rename(per_scl = "3. Sclerotia, %",
         no_samples = "No. of samples")

#2018
sf_201718_df <- sf_2018_1 %>% 
  full_join(sf_2018_2) %>% 
  full_join(sf_2018_3) %>% 
  full_join(sf_2018_4) %>% 
  mutate(harvest_year = 2018) %>% 
  rename(desc = Region) %>% 
    filter(desc %in% c("3. Sclerotia, %", "No. of samples")) %>% 
  distinct() %>%
 pivot_longer(cols = c(2:20),
               names_to = "region",
               values_to = "per_sclerotia") %>% 
  pivot_wider(names_from = "desc",
              values_from = "per_sclerotia") %>% 
  rename(per_scl = "3. Sclerotia, %",
         no_samples = "No. of samples")

#2019
sf_201819_df <-sf_2019_1 %>% 
  full_join(sf_2019_2) %>% 
  full_join(sf_2019_3) %>% 
  full_join(sf_2019_4) %>% 
  mutate(harvest_year = 2019) %>% 
  rename(desc = Region) %>% 
    filter(desc %in% c("3. Sclerotia, %", "No. of samples")) %>% 
  distinct() %>%
 pivot_longer(cols = c(2:22),
               names_to = "region",
               values_to = "per_sclerotia") %>% 
  pivot_wider(names_from = "desc",
              values_from = "per_sclerotia") %>% 
  rename(per_scl = "3. Sclerotia, %",
         no_samples = "No. of samples")

#2020
sf_201920_df <- sf_2020_1 %>% 
  full_join(sf_2020_2) %>% 
  full_join(sf_2020_3) %>% 
  full_join(sf_2020_4) %>% 
  mutate(harvest_year = 2020) %>% 
  rename(desc = Region) %>% 
    filter(desc %in% c("3. Sclerotia, %", "No. of samples")) %>% 
  distinct() %>%
 pivot_longer(cols = c(2:21),
               names_to = "region",
               values_to = "per_sclerotia") %>% 
  pivot_wider(names_from = "desc",
              values_from = "per_sclerotia") %>% 
  rename(per_scl = "3. Sclerotia, %",
         no_samples = "No. of samples")

sf_df <- sf_201213_df %>% 
  full_join(sf_201314_df) %>% 
  full_join(sf_201415_df) %>% 
  full_join(sf_201516_df) %>% 
  full_join(sf_201617_df) %>% 
  full_join(sf_201718_df) %>% 
  full_join(sf_201819_df) %>% 
  full_join(sf_201920_df) %>%
  mutate(over_th = case_when(per_scl == 0 ~ "No sclerotia detected",
                             per_scl > 0 & per_scl < 0.2 ~ "Under all thresholds",
                             per_scl >= 0.2 & per_scl < 4 ~ "Above SANSOR threshold (0.2%)",
                             per_scl >=4 ~ "Above DAFF threshold (4%)"))
```

### silo regions

```{r}
silo_regions <- read.csv("data/silo_regions.csv") %>% select(-X)

silo_regions <- silo_regions %>% 
  rename(region = number)

silo_regions$region <- as.character(silo_regions$region)
```

### full df
```{r}
sf_silo <- sf_df %>% full_join(silo_regions) #note there will be NAs introduced as some years there were no recording/reportings of sclerotia at particular silo points.
```

## soybean 

```{r}
#2011-2012
sb_2012_1 <- read_xlsx("data/soyabean/soya_part_1_2011_2012.xls.xlsx")
sb_2012_2 <- read_xlsx("data/soyabean/soya_part_2_2011_2012.xls.xlsx")
sb_2012_3 <- read_xlsx("data/soyabean/soya_part_3_2011_2012.xls.xlsx")
sb_2012_4 <- read_xlsx("data/soyabean/soya_part_4_2011_2012.xls.xlsx")

#2012-2013
sb_2013_1 <- read_xlsx("data/soyabean/soya_part_1_2012_2013.xls.xlsx")
sb_2013_2 <- read_xlsx("data/soyabean/soya_part_2_2012_2013.xls.xlsx")
sb_2013_3 <- read_xlsx("data/soyabean/soya_part_3_2012_2013.xls.xlsx")
sb_2013_4 <- read_xlsx("data/soyabean/soya_part_4_2012_2013.xls.xlsx")

#2013-2014
sb_2014_1 <- read_xlsx("data/soyabean/soya_part_1_2013_2014.xls.xlsx")
sb_2014_2 <- read_xlsx("data/soyabean/soya_part_2_2013_2014.xls.xlsx")
sb_2014_3 <- read_xlsx("data/soyabean/soya_part_3_2013_2014.xls.xlsx")
sb_2014_4 <- read_xlsx("data/soyabean/soya_part_4_2013_2014.xls.xlsx")
sb_2014_5 <- read_xlsx("data/soyabean/soya_part_5_2013_2014.xls.xlsx")

#2014-2015
sb_2015_1 <- read_xlsx("data/soyabean/soya_part_1_2014_2015.xls.xlsx")
sb_2015_2 <- read_xlsx("data/soyabean/soya_part_2_2014_2015.xls.xlsx")
sb_2015_3 <- read_xlsx("data/soyabean/soya_part_3_2014_2015.xls.xlsx")
sb_2015_4 <- read_xlsx("data/soyabean/soya_part_4_2014_2015.xls.xlsx")

#2015-2016
sb_2016_1 <- read_xlsx("data/soyabean/soya_part_1_2015_2016.xls.xlsx")
sb_2016_2 <- read_xlsx("data/soyabean/soya_part_2_2015_2016.xls.xlsx")
sb_2016_3 <- read_xlsx("data/soyabean/soya_part_3_2015_2016.xls.xlsx")
sb_2016_4 <- read_xlsx("data/soyabean/soya_part_4_2015_2016.xls.xlsx")

#2016-2017
sb_2017_1 <- read_xlsx("data/soyabean/soya_part_1_2016_2017.xls.xlsx")
sb_2017_2 <- read_xlsx("data/soyabean/soya_part_2_2016_2017.xls.xlsx")
sb_2017_3 <- read_xlsx("data/soyabean/soya_part_3_2016_2017.xls.xlsx")
sb_2017_4 <- read_xlsx("data/soyabean/soya_part_4_2016_2017.xls.xlsx")

#2017-2018
sb_2018_1 <- read_xlsx("data/soyabean/soya_part_1_2017_2018.xls.xlsx")
sb_2018_2 <- read_xlsx("data/soyabean/soya_part_2_2017_2018.xls.xlsx")
sb_2018_3 <- read_xlsx("data/soyabean/soya_part_3_2017_2018.xls.xlsx")
sb_2018_4 <- read_xlsx("data/soyabean/soya_part_4_2017_2018.xls.xlsx")

#2018-2019
sb_2019_1 <- read_xlsx("data/soyabean/soya_part_1_2018_2019.xls.xlsx")
sb_2019_2 <- read_xlsx("data/soyabean/soya_part_2_2018_2019.xls.xlsx")
sb_2019_3 <- read_xlsx("data/soyabean/soya_part_3_2018_2019.xls.xlsx")

#2019-2020
sb_2020_1 <- read_xlsx("data/soyabean/soya_part_1_2019_2020.xls.xlsx")
sb_2020_2 <- read_xlsx("data/soyabean/soya_part_2_2019_2020.xls.xlsx")
sb_2020_3 <- read_xlsx("data/soyabean/soya_part_3_2019_2020.xls.xlsx")
sb_2020_4 <- read_xlsx("data/soyabean/soya_part_4_2019_2020.xls.xlsx")
```

### join
```{r}
#2012
sb_2012_1[,2:7]<- lapply(sb_2012_1[,2:7], as.character) #sample number name needed to be changed in raw files
sb_2012_2[,2:7]<- lapply(sb_2012_2[,2:7], as.character)
sb_2012_3[,2:7]<- lapply(sb_2012_3[,2:7], as.character)
sb_2012_4[,2:6]<- lapply(sb_2012_4[,2:6], as.character)

sb_201112_df <- sb_2012_1 %>% #10-15
  full_join(sb_2012_2) %>% #17-24
  full_join(sb_2012_3) %>% #25-30
  full_join(sb_2012_4) %>% #31-36
  dplyr::mutate(harvest_year = "2012") %>% 
  rename(desc = Region) %>% 
  filter(desc %in% c("(F) Sclerotia, %", "No. of samples_scl")) %>% 
  distinct() %>%
 pivot_longer(cols = c(2:24),
               names_to = "region",
               values_to = "per_sclerotia") %>% 
  pivot_wider(names_from = "desc",
              values_from = "per_sclerotia") %>%  #seems to be an error here...
  rename(per_scl = "(F) Sclerotia, %",
         no_samples = "No. of samples_scl")

#2013
sb_2013_1[,2:7]<- lapply(sb_2013_1[,2:7], as.character)
sb_2013_2[,2:7]<- lapply(sb_2013_2[,2:7], as.character)
sb_2013_3[,2:7]<- lapply(sb_2013_3[,2:7], as.character)
sb_2013_4[,2]<- lapply(sb_2013_4[,2], as.character)

sb_201213_df <- sb_2013_1 %>% 
  full_join(sb_2013_2) %>% 
  full_join(sb_2013_3) %>% 
  full_join(sb_2013_4) %>% 
  mutate(harvest_year = "2013") %>% 
  rename(desc = Region) %>% 
  filter(desc %in% c("(F) Sclerotia, %", "No. of samples_scl")) %>% 
  distinct() %>%
 pivot_longer(cols = c(2:20),
               names_to = "region",
               values_to = "per_sclerotia") %>% 
  pivot_wider(names_from = "desc",
              values_from = "per_sclerotia") %>% 
  rename(per_scl = "(F) Sclerotia, %",
         no_samples = "No. of samples_scl")

#2014 
sb_2014_1[,2:7]<- lapply(sb_2014_1[,2:7], as.character)
sb_2014_2[,2:7]<- lapply(sb_2014_2[,2:7], as.character)
sb_2014_3[,2:7]<- lapply(sb_2014_3[,2:7], as.character)
sb_2014_4[,2:7]<- lapply(sb_2014_4[,7], as.character)
sb_2014_5[,2]<- lapply(sb_2014_5[,2], as.character)

sb_201314_df <- sb_2014_1 %>% 
  full_join(sb_2014_2) %>% 
  full_join(sb_2014_3) %>% 
  full_join(sb_2014_4) %>% 
  full_join(sb_2014_5) %>% 
  mutate(harvest_year = "2014") %>% 
  rename(desc = Region) %>% 
    filter(desc %in% c("(F) Sclerotia, %", "No. of samples_scl")) %>% 
  distinct() %>%
 pivot_longer(cols = c(2:26),
               names_to = "region",
               values_to = "per_sclerotia") %>% 
  pivot_wider(names_from = "desc",
              values_from = "per_sclerotia") %>% 
  rename(per_scl = "(F) Sclerotia, %",
         no_samples = "No. of samples_scl")

#2015
sb_2015_1[,2:7]<- lapply(sb_2015_1[,2:7], as.character)
sb_2015_2[,2:7]<- lapply(sb_2015_2[,2:7], as.character)
sb_2015_3[,2:7]<- lapply(sb_2015_3[,2:7], as.character)
sb_2015_4[,2]<- lapply(sb_2015_4[,2], as.character)

sb_201415_df <- sb_2015_1 %>% 
  full_join(sb_2015_2) %>% 
  full_join(sb_2015_3) %>% 
  full_join(sb_2015_4) %>% 
  mutate(harvest_year = "2015") %>% 
  rename(desc = Region) %>% 
    filter(desc %in% c("(F) Sclerotia, %", "No. of samples_scl")) %>% 
  distinct() %>%
 pivot_longer(cols = c(2:25),
               names_to = "region",
               values_to = "per_sclerotia") %>% 
  pivot_wider(names_from = "desc",
              values_from = "per_sclerotia") %>% 
  rename(per_scl = "(F) Sclerotia, %",
         no_samples = "No. of samples_scl")

#2016
sb_2016_1[,2:7]<- lapply(sb_2016_1[,2:7], as.character)
sb_2016_2[,2:7]<- lapply(sb_2016_2[,2:7], as.character)
sb_2016_3[,2:7]<- lapply(sb_2016_3[,2:7], as.character)
sb_2016_4[,2:5]<- lapply(sb_2016_4[,2:5], as.character)

sb_201516_df <- sb_2016_1 %>% 
  full_join(sb_2016_2) %>% 
  full_join(sb_2016_3) %>% 
  full_join(sb_2016_4) %>% 
  mutate(harvest_year = "2016") %>% 
  rename(desc = Region) %>% 
    filter(desc %in% c("(F) Sclerotia, %", "No. of samples_scl")) %>% 
  distinct() %>%
 pivot_longer(cols = c(2:23),
               names_to = "region",
               values_to = "per_sclerotia") %>% 
  pivot_wider(names_from = "desc",
              values_from = "per_sclerotia") %>% 
  rename(per_scl = "(F) Sclerotia, %",
         no_samples = "No. of samples_scl")

#2017
sb_2017_1[,2:7]<- lapply(sb_2017_1[,2:7], as.character)
sb_2017_2[,2:7]<- lapply(sb_2017_2[,2:7], as.character)
sb_2017_3[,2:7]<- lapply(sb_2017_3[,2:7], as.character)
sb_2017_4[,2:3]<- lapply(sb_2017_4[,2:3], as.character)

sb_201617_df <- sb_2017_1 %>% 
  full_join(sb_2017_2) %>% 
  full_join(sb_2017_3) %>% 
  full_join(sb_2017_4) %>% 
  mutate(harvest_year = "2017") %>% 
  rename(desc = Region) %>% 
    filter(desc %in% c("(F) Sclerotia, %", "No. of samples_scl")) %>% 
  distinct() %>%
 pivot_longer(cols = c(2:21),
               names_to = "region",
               values_to = "per_sclerotia") %>% 
  pivot_wider(names_from = "desc",
              values_from = "per_sclerotia") %>% 
  rename(per_scl = "(F) Sclerotia, %",
         no_samples = "No. of samples_scl")

#2018
sb_2018_1[,2:7]<- lapply(sb_2018_1[,2:7], as.character)
sb_2018_2[,2:7]<- lapply(sb_2018_2[,2:7], as.character)
sb_2018_3[,2:7]<- lapply(sb_2018_3[,2:7], as.character)
sb_2018_4[,2]<- lapply(sb_2018_4[,2], as.character)

sb_201718_df <- sb_2018_1 %>% 
  full_join(sb_2018_2) %>% 
  full_join(sb_2018_3) %>% 
  full_join(sb_2018_4) %>% 
  mutate(harvest_year = "2018") %>% 
  rename(desc = Region) %>% 
    filter(desc %in% c("(F) Sclerotia, %", "No. of samples_scl")) %>% 
  distinct() %>%
 pivot_longer(cols = c(2:20),
               names_to = "region",
               values_to = "per_sclerotia") %>% 
  pivot_wider(names_from = "desc",
              values_from = "per_sclerotia") %>% 
  rename(per_scl = "(F) Sclerotia, %",
         no_samples = "No. of samples_scl")

#2019
sb_2019_1[,2:7]<- lapply(sb_2019_1[,2:7], as.character)
sb_2019_2[,2:7]<- lapply(sb_2019_2[,2:7], as.character)
sb_2019_3[,2:7]<- lapply(sb_2019_3[,2:7], as.character)

sb_201819_df <- sb_2019_1 %>% 
  full_join(sb_2019_2) %>% 
  full_join(sb_2019_3) %>% 
  mutate(harvest_year = "2019") %>% 
  rename(desc = Region) %>% 
    filter(desc %in% c("(F) Sclerotia, %", "No. of samples_scl")) %>% 
  distinct() %>%
 pivot_longer(cols = c(2:19),
               names_to = "region",
               values_to = "per_sclerotia") %>% 
  pivot_wider(names_from = "desc",
              values_from = "per_sclerotia") %>% 
  rename(per_scl = "(F) Sclerotia, %",
         no_samples = "No. of samples_scl")

#2020
sb_2020_1[,2:7]<- lapply(sb_2020_1[,2:7], as.character)
sb_2020_2[,2:7]<- lapply(sb_2020_2[,2:7], as.character)
sb_2020_3[,2:7]<- lapply(sb_2020_3[,2:7], as.character)
sb_2020_4[,2:6]<- lapply(sb_2020_4[,2:6], as.character)

sb_201920_df <- sb_2020_1 %>% 
  full_join(sb_2020_2) %>% 
  full_join(sb_2020_3) %>% 
  full_join(sb_2020_4) %>% 
  mutate(harvest_year = "2020") %>% 
  rename(desc = Region) %>% 
    filter(desc %in% c("(F) Sclerotia, %", "No. of samples_scl")) %>% 
  distinct() %>%
 pivot_longer(cols = c(2:24),
               names_to = "region",
               values_to = "per_sclerotia") %>% 
  pivot_wider(names_from = "desc",
              values_from = "per_sclerotia") %>% 
  rename(per_scl = "(F) Sclerotia, %",
         no_samples = "No. of samples_scl")

sb_df <- sb_201213_df %>% 
  full_join(sb_201314_df) %>% 
  full_join(sb_201415_df) %>% 
  full_join(sb_201516_df) %>% 
  full_join(sb_201617_df) %>% 
  full_join(sb_201718_df) %>% 
  full_join(sb_201819_df) %>% 
  full_join(sb_201920_df) %>%
  mutate(over_th = case_when(per_scl == 0 ~ "No sclerotia detected",
                             per_scl > 0 & per_scl < 0.2 ~ "Under all thresholds",
                             per_scl >= 0.2 & per_scl < 4 ~ "Above SANSOR threshold (0.2%)",
                             per_scl >=4 ~ "Above DAFF threshold (4%)"))
```

### full df
```{r}
sb_silo <- sb_df %>% full_join(silo_regions) #note there will be NAs introduced as some years there were no recording/reportings of sclerotia at particular silo points.
```

```{r}
sb_silo$harvest_year <- as.numeric(sb_silo$harvest_year)

sb_silo <-sb_silo %>% 
  mutate(crop = "Soybean")

sf_silo <- sf_silo %>% 
  mutate(crop = "Sunflower")

scl_df <- sf_silo %>% full_join(sb_silo) %>% 
  drop_na(over_th)
```

# analyses

## prevalence
We create a df for the prevalence of sclerotia recovered from the production regions
Where prevalnce is defined as the positive events of sclerotia in relation to total sample collected regardless of legislative limitation.  
```{r prevalence df}
prev = scl_df %>% 
  mutate(freq = case_when(per_scl > 0 ~ 1, 
                          per_scl <= 0 ~ 0)) %>% 
  group_by(crop, harvest_year, freq) %>% 
  summarise(count = n()) %>% 
  full_join(scl_df %>%
  mutate(total = case_when(per_scl > 0 ~ 1, 
                           per_scl <= 0 ~ 0)) %>% 
  group_by(crop, harvest_year) %>% 
  summarise(total = n()))

prev = prev %>% 
  filter(freq >= 1) %>% 
    mutate(prev = count/total*100) %>% 
  dplyr::select(crop, harvest_year, total, prev)

write.csv(prev, "tables/scl_recovery.csv")
```